/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "institutional-navy": "#1B2838",
        "institutional-navy-light": "#243447",
        "institutional-navy-lighter": "#2D4056",
        "institutional-navy-dark": "#111C28",
        "gold-accent": "#C9963B",
        "gold-accent-hover": "#D4A84D",
        "gold-accent-muted": "#8B6B2A",
        "gold-accent-10": "rgba(201,150,59,0.10)",
        "status-compliant": "#2E8B57",
        "status-compliant-bg": "rgba(46,139,87,0.12)",
        "status-warning": "#E8943A",
        "status-warning-bg": "rgba(232,148,58,0.12)",
        "status-critical": "#C73E3E",
        "status-critical-bg": "rgba(199,62,62,0.12)",
        "status-info": "#3A7CC7",
        "status-info-bg": "rgba(58,124,199,0.12)",
        "bg-primary": "#F0F2F5",
        "bg-card": "#FFFFFF",
        "bg-elevated": "#FAFBFC",
        "text-primary": "#1B2838",
        "text-secondary": "#5C6B7A",
        "text-muted": "#8899AA",
        "border-default": "#DDE3E8",
        "border-subtle": "#EDF1F4",
        "bg-dark-primary": "#111C28",
        "bg-dark-card": "#1B2838",
        "bg-dark-elevated": "#243447",
        "text-dark-primary": "#E8ECF0",
        "text-dark-secondary": "#9AABBD",
        "text-dark-muted": "#5C6B7A",
        "border-dark": "#2D4056",
        "bf-red": "#C73E3E",
        "bf-green": "#2E8B57",
        "bf-gold": "#C9963B",
        "chart-blue": "#3A7CC7",
        "chart-gold": "#C9963B",
        "chart-green": "#2E8B57",
        "chart-red": "#C73E3E",
        "chart-orange": "#E8943A",
        "chart-purple": "#7C5CC9",
        "chart-teal": "#2D9CDB",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "playfair-display": ["Playfair Display", "Georgia", "serif"],
        "inter": ["Inter", "system-ui", "sans-serif"],
        "jetbrains-mono": ["JetBrains Mono", "'Courier New'", "monospace"],
        sans: ["Inter", "system-ui", "sans-serif"],
        serif: ["Playfair Display", "Georgia", "serif"],
        mono: ["JetBrains Mono", "'Courier New'", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          "0%": { opacity: "0", transform: "translateX(10px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(1.05)" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.4s ease-out forwards",
        "slide-in": "slide-in 0.25s ease-out forwards",
        "shimmer": "shimmer 1.5s infinite linear",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
