# ============================================================================
# MinIO — Persistent Volume Claims
# ============================================================================

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: ireg-moto-bf-prod
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: ireg-moto-bf
  annotations:
    backup.velero.io/backup-volumes: minio-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 200Gi
