export enum ActorType {
  IMPORTATEUR = 'IMPORTATEUR',
  DISTRIBUTEUR = 'DISTRIBUTEUR',
  ASSEMBLEUR = 'ASSEMBLEUR',
  DETAILLANT = 'DETAILLANT',
  PRESTATAIRE = 'PRESTATAIRE',
}

export enum ActorStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

export enum AgreementStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  RENEWAL_PENDING = 'RENEWAL_PENDING',
}
