export enum IdDocumentType {
  CNI = 'CNI',
  PASSPORT = 'PASSPORT',
  CARTE_CONSULAIRE = 'CARTE_CONSULAIRE',
  NIF_CARD = 'NIF_CARD',
  PERMIS_CONDUIRE = 'PERMIS_CONDUIRE',
  CERTIFICAT_NAISSANCE = 'CERTIFICAT_NAISSANCE',
}

export enum ClientStatus {
  PENDING_KYC = 'PENDING_KYC',
  KYC_VERIFIED = 'KYC_VERIFIED',
  KYC_REJECTED = 'KYC_REJECTED',
  BLACKLISTED = 'BLACKLISTED',
}

export enum BiometricType {
  FINGERPRINT_LEFT_THUMB = 'FINGERPRINT_LEFT_THUMB',
  FINGERPRINT_RIGHT_THUMB = 'FINGERPRINT_RIGHT_THUMB',
  FINGERPRINT_LEFT_INDEX = 'FINGERPRINT_LEFT_INDEX',
  FINGERPRINT_RIGHT_INDEX = 'FINGERPRINT_RIGHT_INDEX',
  PHOTO_FACE = 'PHOTO_FACE',
  SIGNATURE = 'SIGNATURE',
}
