export enum FraudAlertSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum FraudAlertStatus {
  OPEN = 'OPEN',
  UNDER_INVESTIGATION = 'UNDER_INVESTIGATION',
  CONFIRMED = 'CONFIRMED',
  FALSE_POSITIVE = 'FALSE_POSITIVE',
  CLOSED = 'CLOSED',
  ESCALATED = 'ESCALATED',
}

export enum TransactionFlagType {
  PRICE_ANOMALY = 'PRICE_ANOMALY',
  VOLUME_ANOMALY = 'VOLUME_ANOMALY',
  CIRCULAR_TRADE = 'CIRCULAR_TRADE',
  BLACKLISTED_VEHICLE = 'BLACKLISTED_VEHICLE',
  SUSPICIOUS_CLIENT = 'SUSPICIOUS_CLIENT',
  GEO_ANOMALY = 'GEO_ANOMALY',
  TIMING_ANOMALY = 'TIMING_ANOMALY',
  MULTIPLE_SAME_DAY = 'MULTIPLE_SAME_DAY',
}
