export enum MovementType {
  IMPORT = 'IMPORT',
  ASSEMBLY = 'ASSEMBLY',
  TRANSFER = 'TRANSFER',
  SALE = 'SALE',
  RETURN = 'RETURN',
  ADJUSTMENT = 'ADJUSTMENT',
  SCRAP = 'SCRAP',
  RESERVATION = 'RESERVATION',
  RELEASE = 'RELEASE',
}

export enum InventoryStatus {
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  RECONCILED = 'RECONCILED',
  DISCREPANCY_FOUND = 'DISCREPANCY_FOUND',
}
