export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN_DRCTT = 'ADMIN_DRCTT',
  CONTROLEUR = 'CONTROLEUR',
  IMPORTATEUR = 'IMPORTATEUR',
  DISTRIBUTEUR = 'DISTRIBUTEUR',
  ASSEMBLEUR = 'ASSEMBLEUR',
  DETAILLANT = 'DETAILLANT',
  AUDITEUR = 'AUDITEUR',
  CNTI_AGENT = 'CNTI_AGENT',
  // Additional roles for test data and registration
  MINISTRY_INSPECTOR = 'MINISTRY_INSPECTOR',
  MINISTRY_ANALYST = 'MINISTRY_ANALYST',
  ENTERPRISE_ADMIN = 'ENTERPRISE_ADMIN',
  ENTERPRISE_MANAGER = 'ENTERPRISE_MANAGER',
  ENTERPRISE_SELLER = 'ENTERPRISE_SELLER',
  ENTERPRISE_ACCOUNTANT = 'ENTERPRISE_ACCOUNTANT',
}
