export enum VehicleCategory {
  CYCLOMOTEUR_50CC = 'CYCLOMOTEUR_50CC',
  MOTO_LEGERE_125CC = 'MOTO_LEGERE_125CC',
  MOTO_LOURDE_125CC_PLUS = 'MOTO_LOURDE_125CC_PLUS',
  TRICYCLE_MOTEUR = 'TRICYCLE_MOTEUR',
  QUADRACYCLE = 'QUADRACYCLE',
  ELECTRIQUE_50CC_EQ = 'ELECTRIQUE_50CC_EQ',
  ELECTRIQUE_125CC_EQ = 'ELECTRIQUE_125CC_EQ',
  ELECTRIQUE_PLUS = 'ELECTRIQUE_PLUS',
  INTERDITE = 'INTERDITE',
}

export enum FuelType {
  ESSENCE = 'ESSENCE',
  DIESEL = 'DIESEL',
  ELECTRIQUE = 'ELECTRIQUE',
  HYBRIDE = 'HYBRIDE',
  GPL = 'GPL',
}

export enum Transmission {
  MANUELLE = 'MANUELLE',
  AUTOMATIQUE = 'AUTOMATIQUE',
  SEMI_AUTOMATIQUE = 'SEMI_AUTOMATIQUE',
  CONTINUOUSLY_VARIABLE = 'CONTINUOUSLY_VARIABLE',
}

export enum VehicleStatus {
  IMPORTED = 'IMPORTED',
  IN_STOCK = 'IN_STOCK',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  REGISTERED = 'REGISTERED',
  STOLEN = 'STOLEN',
  SCRAPPED = 'SCRAPPED',
  EXPORTED = 'EXPORTED',
}

export enum BlacklistReason {
  STOLEN = 'STOLEN',
  FRAUD = 'FRAUD',
  COUNTERFEIT = 'COUNTERFEIT',
  NON_COMPLIANT = 'NON_COMPLIANT',
  ADMIN_SEIZURE = 'ADMIN_SEIZURE',
  INSURANCE_TOTAL_LOSS = 'INSURANCE_TOTAL_LOSS',
}
